backend:
  name: git-gateway
  branch: main # или master

# Куда сохранять загруженные клиентом картинки
media_folder: "img"
public_folder: "/img"

# Описание разделов (коллекций) для редактирования
collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "index.html" # или data/home.json
        label: "Главная страница"
        name: "home"
        fields:
          - { label: "Заголовок H1", name: "title", widget: "string" }
          - { label: "Подзаголовок", name: "subtitle", widget: "string" }
          - { label: "Текст о нас", name: "about_text", widget: "markdown" }
          - { label: "Главный баннер", name: "hero_image", widget: "image" }